---
version: "3.7"
services:
  cucumber:
    image: carlosnunez/cucumber:master
    volumes:
      - "$PWD:/app"
    working_dir: /app
    command: --version
  gpg:
    image: vladgh/gpg
    volumes:
      - "$PWD:/app"
    working_dir: /app
    command: --version
